version: "3.7"

services:
    proxy:
      image: traefik:v2.2
      ports:
        - "80:80"
        - "443:443"
        - "8089:8080"
      volumes:
        - "./config:/etc/traefik"
        - "./acme.json:/acme.json"
